// <auto-generated />
namespace EkusheBoiMela.Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UserModeladded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserModeladded));
        
        string IMigrationMetadata.Id
        {
            get { return "201401200820135_User Model added.."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
